import assert from 'node:assert/strict';
import fs from 'node:fs';

const app = fs.readFileSync(new URL('../app.js', import.meta.url), 'utf8');
const html = fs.readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const css = fs.readFileSync(new URL('../style.css', import.meta.url), 'utf8');
const serviceWorker = fs.readFileSync(new URL('../sw.js', import.meta.url), 'utf8');
const gitignore = fs.readFileSync(new URL('../.gitignore', import.meta.url), 'utf8');
const pleasureManifest = JSON.parse(fs.readFileSync(new URL('../audio/ambience-manifest.json', import.meta.url), 'utf8'));
const en = JSON.parse(fs.readFileSync(new URL('../locales/en.json', import.meta.url), 'utf8'));
const ml = JSON.parse(fs.readFileSync(new URL('../locales/ml.json', import.meta.url), 'utf8'));
assert.match(gitignore, /audio\/pleasure\.\*/, 'the locally supplied pleasure ambience should not be committed');
assert.match(gitignore, /audio\/pleasure-\*/, 'future pleasure ambience layers should remain local-only regardless of extension');
assert.doesNotMatch(serviceWorker, /audio\/pleasure\.mp3/, 'an optional local-only asset must not break service-worker installation when absent');
assert.match(serviceWorker, /audio\/ambience-manifest\.json/, 'the pleasure asset manifest should be available offline');
assert.match(serviceWorker, /function isPleasureRequest\(request\)/, 'pleasure requests should have an explicit cache policy');
assert.match(serviceWorker, /isPleasureRequest\(event\.request\)[\s\S]*?fetch\(event\.request, \{ cache: 'no-store' \}\)/, 'the service worker should revalidate pleasure files instead of serving moved assets from cache');
assert.deepEqual(pleasureManifest.files, ['pleasure.mp3', 'pleasure-1.ogg'], 'the pleasure manifest should list the current overlay layers');

assert.match(html, /id="music-tuning-panel"/, 'the mixer should expose a separate background-music tuning panel');
assert.match(html, /id="music-echo"/, 'the mixer should expose a separate music echo selector');
assert.match(html, /data-i18n="ui\.musicEcho"/, 'the music echo selector should use localized labels');
assert.match(html, /id="mood-relaxation-ambience-level-control"[^>]*hidden/, 'the ambience level control should be hidden until the ambience is selected');
assert.match(html, /id="mood-relaxation-intention-toggle"/, 'Journey Tuning should expose the ambience toggle');
assert.match(html, /id="pleasure-ambience-intensity-control"[^>]*hidden/, 'the ambience intensity selector should be hidden until the ambience is selected');
assert.match(html, /id="pleasure-ambience-intensity"/, 'Journey Tuning should expose a session-only ambience intensity selector');
assert.match(html, /id="pleasure-ambience-url-control"[^>]*hidden/, 'the pleasure URL control should be hidden until the ambience is selected');
assert.match(html, /id="pleasure-ambience-url"[^>]*type="url"/, 'Journey Tuning should expose a URL input for the primary pleasure track');
assert.match(html, /id="load-pleasure-ambience-url"[^>]*data-i18n="ui\.loadPleasureAmbience"/, 'the pleasure URL input should have a localized Load action');
assert.match(html, /data-i18n-placeholder="ui\.pleasureAmbienceUrlPlaceholder"/, 'the pleasure URL input should use a localized placeholder');
assert.match(html, /id="pleasure-ambience-url-note"[^>]*data-i18n="ui\.pleasureAmbienceUrlNote"/, 'the pleasure URL input should explain the primary-layer replacement and CORS requirement');
assert.match(css, /\.mixer-url-entry input\[type="url"\]\s*\{[\s\S]*?flex:\s*1 1 0;/, 'the pleasure URL input should take the remaining row width');
assert.match(css, /\.mixer-url-entry \.secondary-btn\s*\{[\s\S]*?width:\s*auto;[\s\S]*?max-width:\s*7\.5rem;/, 'the pleasure URL Load action should remain compact instead of expanding to the full row');
assert.match(html, /id="pleasure-ambience-blur-toggle"[^>]*checked/, 'pleasure ambience blur should be enabled by default');
assert.match(html, /id="pleasure-ambience-blur-control"[^>]*hidden/, 'pleasure blur should appear only when ambience is selected');
assert.match(html, /id="pleasure-ambience-blur-level-control"[^>]*hidden/, 'pleasure blur intensity should appear only when ambience is selected');
assert.match(html, /id="pleasure-ambience-blur-level"[^>]*min="10"[^>]*max="65"[^>]*step="5"[^>]*value="35"/, 'pleasure blur should have a higher 35% default with bounded intensity');
assert.match(html, /id="mood-relaxation-ambience-level"[^>]*min="0\.2"[^>]*max="7\.0"[^>]*step="0\.1"/, 'the ambience level slider should skip the first non-zero step and retain its 7.0% maximum');
const ambienceControl = html.match(/<div id="mood-relaxation-ambience-level-control"[\s\S]*?<\/div>\s*<\/div>/)?.[0] || '';
assert.equal((ambienceControl.match(/class="range-meta"/g) || []).length, 1, 'the ambience control should contain one metadata row');
assert.match(ambienceControl, /range-decrement[\s\S]*range-min[\s\S]*range-current[\s\S]*range-max[\s\S]*range-increment/, 'the ambience metadata row should keep both step buttons inline');
assert.match(app, /const existingMeta = container\.querySelector\(':scope > \.range-meta'\)/, 'range enhancement should reuse an existing metadata row');
assert.match(app, /if \(current\.parentElement !== meta\) meta\.appendChild\(current\)/, 'generated range values should be moved into the metadata row before insertion');
assert.match(app, /if \(input\.id === 'mood-relaxation-ambience-level'\) return `\$\{value\.toFixed\(1\)\}%`/, 'the ambience value should remain a percentage in the shared range row');
assert.match(app, /if \(!minimum\.dataset\.i18n\) minimum\.textContent = input\.min/, 'localized range labels should not be overwritten by range updates');
assert.doesNotMatch(css, /#mood-relaxation-ambience-level-control \.range-meta/, 'the ambience control should use the shared five-column range layout');
assert.match(app, /const PLEASURE_AMBIENCE_MAX_GAIN = 0\.07/, 'the ambience engine should enforce the 7.0% maximum');
assert.match(app, /const PLEASURE_AMBIENCE_CONFIRM_THRESHOLD = 0\.05/, 'the ambience engine should require confirmation above 5.0%');
assert.match(app, /requestedGain > PLEASURE_AMBIENCE_CONFIRM_THRESHOLD[\s\S]*?window\.confirm\(t\('ui\.pleasureAmbienceAboveFiveConfirm'\)\)[\s\S]*?syncPleasureAmbienceControl\(\)[\s\S]*?return;/, 'cancelling the high-level confirmation should restore the previous ambience value');
assert.match(app, /const PLEASURE_AMBIENCE_MIN_GAIN = 0\.002/, 'the ambience engine should skip the first non-zero step');
assert.doesNotMatch(app, /localStorage\.getItem\('chakra_mood_relaxation_intention'\)/, 'the ambience selection must not be restored from local storage');
assert.doesNotMatch(app, /localStorage\.setItem\('chakra_mood_relaxation_intention'/, 'the ambience selection must not be saved to local storage');
assert.match(app, /this\.pleasureLoops\.forEach\(loop => loop\.stop\(Math\.max\(0, fadeTime\)\)\)/, 'all ambience layers should use the same smooth fade');
assert.match(app, /if \(section\) section\.hidden = false/, 'the ambience section should remain available when optional local audio is missing');
assert.match(app, /if \(urlControl\) urlControl\.hidden = !state\.moodRelaxationIntentionEnabled;/, 'a selected ambience should retain its URL recovery control when local audio is missing');
assert.match(app, /t\('ui\.pleasureAmbienceSourceUnavailable'\)/, 'missing local ambience should show a recoverable source message');
assert.doesNotMatch(app, /pleasureAudioAvailable = false;\s*state\.moodRelaxationIntentionEnabled = false;/, 'a missing optional asset must not clear the selected ambience state');
for (const [id, min] of [['vol-voice', '0\.2'], ['vol-drone', '0\.02'], ['vol-bell', '0\.2'], ['vol-mantra', '0\.1'], ['vol-music', '0\.02']]) {
    assert.match(html, new RegExp(`id="${id}"[^>]*min="${min}"`), `${id} should skip the first non-zero step`);
}
assert.match(css, /\.settings-help-content\s*\{[\s\S]*?max-height:\s*calc\(100vh - 2rem\);[\s\S]*?overflow:\s*hidden;/, 'the Help modal should remain within the viewport');
assert.match(css, /\.settings-help-list\s*\{[\s\S]*?overflow-y:\s*auto;/, 'the Help content should scroll inside the modal');

for (const locale of [en, ml]) {
    for (const key of ['musicTuning', 'musicEcho', 'musicEchoOff', 'musicEchoLight', 'musicEchoSpacious', 'musicEchoNote', 'settingsHelpAudioCredit', 'cc0Details', 'moodRelaxationIntention', 'moodRelaxationIntentionNote', 'pleasureAmbienceIntensity', 'pleasureAmbienceGentle', 'pleasureAmbienceImmersive', 'pleasureAmbienceDeep', 'pleasureAmbienceIntensityNote', 'pleasureAmbienceUrl', 'pleasureAmbienceUrlPlaceholder', 'loadPleasureAmbience', 'pleasureAmbienceUrlNote', 'pleasureAmbienceUrlLoading', 'pleasureAmbienceUrlLoaded', 'pleasureAmbienceUrlCleared', 'pleasureAmbienceUrlError', 'pleasureAmbienceSourceUnavailable', 'pleasureAmbienceBlur', 'pleasureAmbienceBlurNote', 'pleasureAmbienceBlurLevel', 'pleasureAmbienceBlurMin', 'pleasureAmbienceBlurMax', 'pleasureAmbienceBlurLevelNote', 'pleasureAmbienceAboveFiveConfirm']) {
        assert.ok(locale.ui[key]?.trim(), `locale ui.${key} is required`);
    }
}

assert.match(app, /musicEchoSend = null/);
assert.match(app, /musicEchoDelay = null/);
assert.match(app, /musicEchoConvolver = null/);
assert.match(app, /musicEchoWetGain = null/);
assert.match(app, /bgMusicBusGain = null/);
assert.match(app, /this\.bgMusicSmoothGain\.connect\(this\.musicEchoSend\)/, 'music echo must receive the shaped background-music signal only');
assert.match(app, /this\.musicEchoWetGain\.connect\(this\.bgMusicBusGain\)/, 'music echo must return to the music-only bus');
assert.match(app, /this\.bgMusicBusGain\.connect\(this\.spatialMusicPanner\)[\s\S]*?this\.spatialMusicPanner\.connect\(this\.lowCutFilter\)/, 'the complete music bus must enter the shared output chain through spatial routing');
assert.match(app, /this\.voiceClarityFilter\.connect\(this\.voiceEchoSend\)/, 'narration echo should remain on the voice-only path');
assert.match(app, /this\.voiceEchoConvolver\.buffer = this\.createDiffuseReverbImpulse\(2\.8, 3\.2, 731\)/, 'narration space should use a deterministic diffuse reverb tail');
assert.match(app, /this\.musicEchoConvolver\.buffer = this\.createDiffuseReverbImpulse\(1\.8, 4\.2, 1777\)/, 'music space should use a deterministic diffuse reverb tail');
assert.doesNotMatch(app, /voiceEchoFeedback|musicEchoFeedback/, 'voice and music space must not contain a repeating feedback loop');
assert.match(app, /const BACKGROUND_MUSIC_ASSET_VERSION = '20260831\.1'/, 'a committed background-music replacement should have an explicit release version');
assert.match(app, /fetch\(BACKGROUND_MUSIC_URL, \{ cache: 'reload' \}\)/, 'the music loader should request the release-versioned asset from the network');
assert.match(serviceWorker, /audio\/background_music\.mp3\?v=20260831\.1/, 'the service worker should precache the matching versioned music asset');
assert.match(app, /const PLEASURE_AMBIENCE_GAIN = 0\.003/, 'pleasure ambience should use a fixed barely-audible gain');
assert.match(app, /const PLEASURE_AMBIENCE_HARMONIC_MIX = 0\.04/, 'pleasure harmonic enrichment should remain a very low parallel mix');
assert.match(app, /const PLEASURE_AMBIENCE_INTENSITIES = Object\.freeze/, 'ambience intensity should use explicit bounded profiles');
assert.match(app, /pleasureAmbienceIntensity: 'gentle'/, 'Gentle should be the default session ambience profile');
assert.doesNotMatch(app, /localStorage\.getItem\('chakra_pleasure_ambience_intensity'\)/, 'ambience intensity must reset rather than persist');
assert.doesNotMatch(app, /localStorage\.setItem\('chakra_pleasure_ambience_intensity'/, 'ambience intensity must not be saved to local storage');
assert.match(app, /translation && translation !== path\) element\.textContent = translation/, 'stale language bundles should preserve readable fallback labels instead of showing raw ui keys');
assert.match(app, /const PLEASURE_BLUR_DEFAULT_AMOUNT = 0\.35/, 'pleasure blur should have a higher 35% default amount');
assert.match(app, /const PLEASURE_BLUR_MAX_AMOUNT = 0\.65/, 'pleasure blur should have a bounded maximum amount');
assert.match(app, /function clampPleasureAmbienceBlurAmount\(value\)/, 'pleasure blur intensity should be clamped before use');
assert.match(app, /const PLEASURE_AMBIENCE_MANIFEST_URL = 'audio\/ambience-manifest\.json'/, 'pleasure files should be loaded from the folder manifest');
assert.match(app, /fetch\(PLEASURE_AMBIENCE_MANIFEST_URL, \{ cache: 'no-store' \}\)/, 'the manifest should not be read from the browser HTTP cache');
assert.match(app, /fetch\(path, \{ cache: 'no-store' \}\)/, 'pleasure audio files should be revalidated when loaded');
assert.match(app, /error\?\.message !== 'HTTP 404'[\s\S]*?console\.warn\(\`\[Pleasure Ambience\] skipped/, 'optional missing pleasure files should stay quiet while other asset failures remain diagnosable');
assert.match(app, /const PLEASURE_AMBIENCE_URL_STORAGE_KEY = 'chakra_pleasure_ambience_url'/, 'the selected pleasure URL should have its own storage key');
assert.match(app, /function normalizePleasureAmbienceUrl\(value\)/, 'pleasure URLs should be normalized before use');
assert.ok(app.includes(".filter(entry => /^pleasure(?:-\\d+)?\\.[^./]+$/i.test(entry))"), 'pleasure layers should support numbered files with any extension');
assert.ok(app.includes("const serialPaths = manifestPaths.filter(path => !/^audio\\/pleasure\\.[^./]+$/i.test(path));"), 'numbered manifest layers should be separated from the replaceable primary track');
assert.match(app, /const paths = customUrl \? \[customUrl, \.\.\.serialPaths\] : manifestPaths/, 'a custom URL should replace only the primary manifest track');
assert.match(app, /async loadPleasureAmbienceUrl\(url\)/, 'the audio engine should expose an explicit URL-loading method');
assert.match(app, /localStorage\.setItem\(PLEASURE_AMBIENCE_URL_STORAGE_KEY, normalizedUrl\)/, 'a successfully loaded URL should be persisted');
assert.match(app, /localStorage\.removeItem\(PLEASURE_AMBIENCE_URL_STORAGE_KEY\)/, 'clearing the URL should restore manifest loading');
assert.match(app, /if \(path === customUrl\) throw new Error\(`Unable to load the pleasure ambience URL/, 'custom URL failures should be reported instead of silently falling through');
assert.match(app, /loadPleasureAmbienceUrlButton\?\.addEventListener\('click', async \(\) =>/, 'the Journey Tuning Load action should call the audio URL loader');
assert.match(app, /this\.pleasureLoops = \[\]/, 'pleasure ambience should support multiple simultaneous loops');
assert.match(app, /this\.pleasureBuffers = new Map\(\)/, 'pleasure ambience buffers should be tracked per file');
assert.ok(app.includes('[...this.pleasureBuffers.values()].map(buffer =>'), 'all decoded pleasure layers should be overlaid');
assert.match(app, /this\.pleasureSourceGain\.connect\(this\.pleasureGain\)/, 'pleasure ambience should retain its clean path');
assert.match(app, /this\.pleasureSourceGain\.connect\(this\.pleasureEnhancer\)/, 'pleasure ambience should have a dedicated harmonic path');
assert.match(app, /this\.pleasureEnhancer\.oversample = '2x'/, 'pleasure harmonic enrichment should use oversampling for cleaner processing');
assert.match(app, /this\.pleasureEnhancerGain\.connect\(this\.pleasureBlurDryGain\)/, 'pleasure harmonic enrichment should enter the blur mix');
assert.match(app, /this\.pleasureGain\.connect\(this\.pleasureBlurDryGain\)/, 'pleasure ambience should use its own blur mix');
assert.match(app, /this\.pleasureLoops = \[\.\.\.this\.pleasureBuffers\.values\(\)\]\.map\(buffer =>/, 'each listed pleasure file should feed its own loop');
assert.match(app, /async startPleasureAmbience\(\)/, 'the pleasure ambience should have an explicit session start method');
assert.match(app, /await this\.loadPleasureAmbienceBuffers\(\)/, 'the pleasure ambience should load its files from the manifest');
assert.match(app, /setPleasureAmbienceIntensity\(intensity = 'gentle'\)/, 'the audio engine should apply a session ambience intensity profile');
assert.match(app, /profile\.blurCutoff/, 'the intensity profile should control blur clarity');
assert.match(app, /profile\.nearDistanceMultiplier/, 'the intensity profile should control spatial presence');
assert.match(app, /pleasure: \{ x: 0, y: 0\.15, z: -6, nearZ: -2\.4 \}/, 'stereo pleasure ambience should approach a closer position');
assert.match(app, /pleasure: \{ x: 0, y: 0\.2, z: -7, nearZ: -2\.8 \}/, 'headphone pleasure ambience should approach a closer position');
assert.match(app, /pleasure: \{ x: 0, y: 0\.25, z: -6\.5, nearZ: -2\.5 \}/, 'room pleasure ambience should approach a closer position');
assert.match(app, /if \(this\.pleasureLoops\.some\(loop => loop\.isRunning\)\) \{[\s\S]*?this\.setPleasureAmbienceIntensity\(state\.pleasureAmbienceIntensity\)[\s\S]*?return true;/, 'an already-running ambience bus should reapply the selected profile');
assert.match(app, /this\.pleasureLoops = \[\.\.\.this\.pleasureBuffers\.values\(\)\]\.map\(buffer =>[\s\S]*?this\.setPleasureAmbienceIntensity\(state\.pleasureAmbienceIntensity\)/, 'every manifest layer should use the selected clarity and spatial profile throughout the journey');
assert.doesNotMatch(app, /fetch\('audio\/pleasure\.mp3'\)/, 'individual pleasure filenames should not be hardcoded in the app');
assert.match(app, /catch \(error\) \{[\s\S]*?pleasureAudioAvailable = false[\s\S]*?return false;/, 'a missing pleasure asset must fail soft without stopping the journey');
assert.match(app, /stopPleasureAmbience\(fadeTime = PLEASURE_AMBIENCE_FADE_SECONDS\)/, 'the pleasure ambience should have an explicit stop method');
assert.match(app, /this\.pleasureManifest = null;[\s\S]*?this\.pleasureBuffers\.clear\(\);/, 'stopping the ambience should clear decoded buffers before the next journey');
assert.match(app, /if \(!state\.bgMusicMode\) void this\.audio\.startPleasureAmbience\(\)/, 'guided sessions should start the pleasure ambience without changing Music Only');
assert.match(app, /this\.audio\.stopPleasureAmbience\(\)/, 'session completion and cancellation should stop the pleasure ambience');
assert.match(app, /pleasureAmbienceGain: clampPleasureAmbienceGain\(storedNumber\('chakra_pleasure_ambience_gain', PLEASURE_AMBIENCE_GAIN\)\)/, 'the ambience level should have a bounded saved preference');
assert.match(app, /setPleasureAmbienceGain\(gain\)/, 'the audio engine should expose a smooth ambience level update');
assert.match(app, /this\.pleasureBlurFilter = this\.ctx\.createBiquadFilter\(\)/, 'pleasure ambience should have a dedicated blur filter');
assert.match(app, /this\.pleasureBlurConvolver\.buffer = this\.createImpulseResponse\(0\.9, 4\.5\)/, 'pleasure blur should use gentle diffusion');
assert.match(app, /setPleasureAmbienceBlur\(enabled = true\)/, 'pleasure blur should be independently toggleable');
assert.match(app, /state\.pleasureAmbienceBlur = true/, 'enabling the ambience should restore blur as the default');
assert.match(app, /pleasureAmbienceBlurAmount: clampPleasureAmbienceBlurAmount\(storedNumber\('chakra_pleasure_ambience_blur_amount', PLEASURE_BLUR_DEFAULT_AMOUNT\)\)/, 'pleasure blur intensity should have a bounded saved preference');
assert.match(app, /pleasure-ambience-blur-level'\)\?\.addEventListener\('input'/, 'the pleasure blur intensity slider should update from user input');
assert.match(app, /mood-relaxation-ambience-level'\)\?\.addEventListener\('input'/, 'the ambience level slider should update from user input');

const setMusicEchoStart = app.indexOf('    setMusicEcho(mode = \'light\')');
const setMusicEchoEnd = app.indexOf('\n    toggleEyesCloseMode(', setMusicEchoStart);
assert.ok(setMusicEchoStart >= 0 && setMusicEchoEnd > setMusicEchoStart, 'setMusicEcho() must remain readable');
const setMusicEcho = app.slice(setMusicEchoStart, setMusicEchoEnd);
assert.match(setMusicEcho, /off: \{ delay: 0\.018, wet: 0, filter: 2800 \}/);
assert.match(setMusicEcho, /light: \{ delay: 0\.018, wet: 0\.12, filter: 2800 \}/);
assert.match(setMusicEcho, /spacious: \{ delay: 0\.035, wet: 0\.18, filter: 3400 \}/);
assert.match(setMusicEcho, /musicEchoSend\.gain\.linearRampToValueAtTime/);
assert.match(setMusicEcho, /musicEchoWetGain\.gain\.linearRampToValueAtTime/);

const mantraStart = app.indexOf('    async playMantraTrack(key)');
const mantraEnd = app.indexOf('    // New: Studio Reverb Swell', mantraStart);
assert.ok(mantraStart >= 0 && mantraEnd > mantraStart, 'mantra audio methods must remain readable');
const mantraBlock = app.slice(mantraStart, mantraEnd);
assert.match(mantraBlock, /this\.stopMantraTrack\(\{ restoreMusic: false, invalidate: false \}\)/);
assert.match(mantraBlock, /this\.muteBackgroundMusicForMantra\(MANTRA_MUSIC_FADE_SECONDS\)/);
assert.ok(
    mantraBlock.indexOf('this.mantraBuffer[key] = await this.ctx.decodeAudioData(arrayBuffer);') <
    mantraBlock.indexOf('const musicFade = this.muteBackgroundMusicForMantra(MANTRA_MUSIC_FADE_SECONDS);'),
    'music mute should begin after first-use mantra decoding to avoid a loading silence',
);
assert.doesNotMatch(mantraBlock, /bgMusicEQ\.gain\.linearRampToValueAtTime\(-12/, 'mantra muting must not rely on partial EQ ducking');
assert.match(mantraBlock, /this\.restoreBackgroundMusicAfterMantra\(\)/, 'failed mantra loading must release the music mute');
assert.match(mantraBlock, /this\.masterGain\.gain\.linearRampToValueAtTime\(state\.volDrone \* 0\.15/, 'drone ducking should remain separate from music muting');

const stopMantraStart = app.indexOf('    stopMantraTrack({ restoreMusic = true, invalidate = true } = {})');
const stopMantraEnd = app.indexOf('    // New: Studio Reverb Swell', stopMantraStart);
const stopMantraBlock = app.slice(stopMantraStart, stopMantraEnd);
assert.match(stopMantraBlock, /linearRampToValueAtTime\(0, now \+ MANTRA_FADE_SECONDS\)/, 'mantra should fade out smoothly');
assert.match(stopMantraBlock, /setTimeout\(\(\) => \{[\s\S]*?restoreBackgroundMusicAfterMantra\(\)/, 'music should remain muted until the mantra fade completes');
assert.match(app, /const BACKGROUND_MUSIC_STOP_FADE_SECONDS = 5/);
assert.match(app, /const BACKGROUND_MUSIC_ENTRY_FADE_SECONDS = 10/);
const backgroundStart = app.indexOf('    async startBackgroundMusic()');
const backgroundEnd = app.indexOf('    async loadPleasureAmbienceBuffers()', backgroundStart);
assert.ok(backgroundStart >= 0 && backgroundEnd > backgroundStart, 'background music startup must remain readable');
const backgroundBlock = app.slice(backgroundStart, backgroundEnd);
assert.match(backgroundBlock, /this\.bgMusicGain\.gain\.setValueAtTime\(0, now\)/, 'background restarts should clear stale outer gain before fading in');
assert.match(backgroundBlock, /this\.bgMusicLoop = new SeamlessLoop\([\s\S]*?BACKGROUND_MUSIC_ENTRY_FADE_SECONDS\n\s*\);/, 'background loop startup should use the full entry fade');
assert.match(app, /const BACKGROUND_MUSIC_RESTORE_FADE_SECONDS = 8/);
assert.match(app, /const MANTRA_MUSIC_FADE_SECONDS = 4/, 'music should receive a deliberate handoff fade before mantra playback');
assert.match(app, /const MANTRA_FADE_SECONDS = 4/, 'mantra should use a deliberate fade when stopping');
assert.match(app, /const PIPER_CLIP_FADE_SECONDS = 0\.05/);
assert.match(app, /const NARRATION_MANTRA_FADE_SECONDS = 2/);
assert.match(app, /const PIPER_CANCEL_FADE_SECONDS = 0\.12/);
assert.match(app, /const requestedFadeIn = Number\(callbacks\.fadeInSeconds\)/, 'Piper should keep the normal clip fade-in separate from the transition fade-out');
assert.match(app, /const requestedFadeOut = Number\(callbacks\.fadeOutSeconds\)/, 'Piper should support an explicit final-clip fade-out');
assert.match(app, /cancel\(reason = 'cancelled', \{ immediate = false \} = \{\}\)/, 'Piper cancellation should distinguish graceful and emergency stops');
assert.match(app, /source\.stop\(now \+ fadeSeconds \+ 0\.02\)/, 'graceful Piper cancellation should ramp the clip down before stopping');
assert.match(app, /piperTTS\.cancel\('experiment stopped', \{ immediate: true \}\)/, 'Experiment stop should cancel active narration immediately');
assert.match(app, /piperTTS\.cancel\('journey finished', \{ immediate: true \}\)/, 'completion should cancel any stale narration immediately');
assert.match(app, /piperTTS\.cancel\('journey stopped', \{ immediate: true \}\)/, 'manual stop should cancel any active narration immediately');
assert.match(app, /const musicFade = this\.muteBackgroundMusicForMantra\(MANTRA_MUSIC_FADE_SECONDS\)[\s\S]*?remainingMs[\s\S]*?await new Promise/, 'mantra should wait for the music fade to finish');
assert.match(app, /if \(invalidate\) this\.mantraRequestId \+= 1/, 'stopping should invalidate pending mantra startup');
assert.match(app, /if \(requestId !== this\.mantraRequestId \|\| state\.noMantraMode\) return;/, 'a cancelled handoff must not start the mantra');
assert.match(app, /cancelAndHoldAtTime\(now\)/, 'the music fade should preserve the live gain value without a jump');
assert.match(app, /const fadeDuration = Math\.max\(0, duration\)[\s\S]*?this\.bgMusicBusGain\.gain\.linearRampToValueAtTime\(0, now \+ fadeDuration\)/, 'music mute should fade the complete music bus to silence');
assert.match(app, /restoreBackgroundMusicAfterMantra\(duration = BACKGROUND_MUSIC_RESTORE_FADE_SECONDS\)[\s\S]*?this\.bgMusicBusGain\.gain\.linearRampToValueAtTime\(1, now \+ Math\.max\(0, duration\)\)/, 'music restore should use a smooth bus fade-in');
assert.match(app, /fadeOutBackgroundMusic\(duration = 4\)[\s\S]*?this\.bgMusicTargetVolume = 0/, 'an intentional music fade-out should remain muted through later slider changes');
assert.match(app, /setBackgroundMusicVolume\(level, previousLevel = level\)[\s\S]*?const roleFactor = Math\.max\(0, Math\.min\(1, currentTarget \/ previous\)\)/, 'music volume updates should preserve the active full, ducked, or silent role');
assert.match(app, /const previousVolume = state\.volMusic;[\s\S]*?audio\.setBackgroundMusicVolume\(state\.volMusic, previousVolume\)/, 'the music slider should use the role-preserving update rather than forcing full gain');
assert.doesNotMatch(app, /this\.bgMusicLoop\.stop\(0\)/, 'background music must never be restarted with an immediate cut');
assert.match(app, /stopBackgroundMusic\(fadeTime = BACKGROUND_MUSIC_STOP_FADE_SECONDS\)[\s\S]*?this\.bgMusicLoop\.stop\(Math\.max\(0, fadeTime\)\)/, 'background music stops should use a controlled fade');
assert.match(app, /stopMantraTrack\(\{ restoreMusic: false \}\)[\s\S]*?fadeOutBackgroundMusic\(BACKGROUND_MUSIC_STOP_FADE_SECONDS\)[\s\S]*?stopBackgroundMusic\(BACKGROUND_MUSIC_STOP_FADE_SECONDS\)/, 'completion should coordinate mantra and music fades without restoring music');
assert.match(app, /musicEcho: localStorage\.getItem\('chakra_music_echo'\) \|\| 'light'/, 'music echo preference should have a safe default');
assert.match(app, /syncValue\('music-echo', state\.musicEcho\)/, 'the music echo selector should restore its saved value');
assert.match(app, /document\.getElementById\('music-echo'\)\?\.addEventListener\('change'/, 'music echo changes should be persisted independently');
assert.match(app, /if \(state\.noMantraMode\) return;/, 'No Mantra Mode should be independent from No Frequency Mode');
assert.match(app, /if \(state\.noFrequencyMode \|\| state\.noMantraMode\) return;/, 'a chakra drone should not start without its mantra');

console.log('Background music mantra mute and echo contract passed.');
