import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source = fs.readFileSync('celestial-presence.js','utf8');
const frames = new Map(); const timers = new Map(); let sequence = 0;
const classes = new Set(); const listeners = {};
const preference = { matches: false, addEventListener() {} };
const canvas = { setAttribute() {}, addEventListener(name, fn) { listeners[name]=fn; }, getBoundingClientRect() { return {width:1200,height:900}; }, getContext() { return null; } };
const image = { src:'root.png', complete:true, naturalWidth:512, naturalHeight:512, addEventListener() {} };
const container = { appendChild() {}, classList: { add(x) {classes.add(x);}, remove(x) {classes.delete(x);} } };
const document = { hidden:false, createElement() {return canvas;}, addEventListener() {} };
const context = { window:{}, document, matchMedia:()=>preference, MutationObserver:class {observe() {}}, ResizeObserver:class {observe() {}},
    setTimeout(fn) {timers.set(++sequence,fn);return sequence;}, clearTimeout(id) {timers.delete(id);},
    requestAnimationFrame(fn) {frames.set(++sequence,fn);return sequence;}, cancelAnimationFrame(id) {frames.delete(id);}, performance:{now:()=>0}, devicePixelRatio:3, Uint8Array };
vm.runInNewContext(source,context);
const scene = new context.window.CelestialPresence(container,image);
scene.setActive(true,'#ddaa77');
assert.equal(classes.has('presence-ready'),false,'No WebGL keeps the original image');
assert.equal(frames.size,0,'Unavailable renderer must not retry every frame');
const values = {};
const gl = { MAX_TEXTURE_SIZE:1, TRIANGLES:4, uniform1f(k,v) {values[k]=v;}, uniform2f() {}, uniform3fv() {}, viewport() {}, drawArrays() {}, getParameter() {return 4096;} };
scene.initialize = () => {scene.gl=gl; return true;};
scene.uploaded=image.src;
scene.uniforms = Object.fromEntries(['time','motion','breath','resonance','tint','imageSize','viewport'].map(k=>[k,k]));
scene.refresh();
assert.ok(classes.has('presence-ready'));
assert.equal(canvas.width,960,'Drawing resolution is bounded on high-DPR displays');
assert.equal(canvas.height,720);
assert.equal(frames.size,0,'No display-rate polling between draws');
assert.equal(timers.size,1);
const [timerId, resume] = timers.entries().next().value;
timers.delete(timerId); resume();
assert.equal(frames.size,1,'A due draw still aligns to display refresh');
scene.setPaused(true);
assert.equal(frames.size,0,'Pause stops GPU frame requests');
assert.equal(timers.size,0,'Pause cancels scheduled work');
const heldTime=scene.time;
scene.refresh(); assert.equal(scene.time,heldTime);
scene.setPaused(false); preference.matches=true; scene.refresh();
assert.equal(frames.size,0,'Reduced motion draws once, not continuously');
assert.equal(timers.size,0);
assert.equal(values.motion,0);
preference.matches=false; document.hidden=true; scene.refresh();
assert.equal(frames.size,0,'Hidden pages release the animation loop');
assert.equal(timers.size,0);
document.hidden=false; scene.refresh();
listeners.webglcontextlost({preventDefault() {}});
assert.equal(classes.has('presence-ready'),false,'Context loss restores the image');
assert.equal(frames.size,0);
scene.setActive(false);
assert.equal(scene.paused,false);
let detached = 0, released = 0;
const analyser = {disconnect(){released++;}};
scene.audio = {mantraGain:{disconnect(target){assert.equal(target,analyser);detached++;}}};
scene.analyser = analyser; scene.samples = new Uint8Array(256);
scene.setActive(false);
scene.setActive(false);
assert.equal(detached,1,'Inactive effects detach only their analyser branch once');
assert.equal(released,1);
assert.equal(scene.samples,null,'Inactive analyser sample memory is released');
assert.match(source,/lit\*base.a/,'Rendering retains source alpha rather than fading all artwork');
assert.match(source,/Math\.exp\(-dt\/2\)/,'Mantra response is smoothed over time');
assert.doesNotMatch(source,/getUserMedia/,'No microphone permission is introduced');
console.log('Sacred Depth lifecycle passed (mock GPU; shader appearance/compilation requires browser verification).');
