import assert from 'node:assert/strict';
import fs from 'node:fs';

const app = fs.readFileSync(new URL('../app.js', import.meta.url), 'utf8');
const openingStage = fs.readFileSync(new URL('../modules/journey-opening-stage.js', import.meta.url), 'utf8');
const prelude = fs.readFileSync(new URL('../modules/journey-video-prelude.js', import.meta.url), 'utf8');
const yogaSession = fs.readFileSync(new URL('../modules/yoga-session.js', import.meta.url), 'utf8');
const careSession = fs.readFileSync(new URL('../modules/care-session.js', import.meta.url), 'utf8');
const journeyChrome = fs.readFileSync(new URL('../modules/journey-chrome.js', import.meta.url), 'utf8');
const html = fs.readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const css = fs.readFileSync(new URL('../tailwind/legacy.css', import.meta.url), 'utf8');
const sw = fs.readFileSync(new URL('../sw.js', import.meta.url), 'utf8');
const locales = ['en', 'ml', 'ru', 'hi', 'ta'].map(language =>
    JSON.parse(fs.readFileSync(new URL(`../locales/${language}.json`, import.meta.url), 'utf8'))
);

assert.ok(fs.statSync(new URL('../video/generate.mp4', import.meta.url)).size > 0, 'the generated compressed prelude video should exist');
assert.ok(fs.statSync(new URL('../video/meditator.png', import.meta.url)).size > 0, 'the supplied meditator image should exist');
assert.match(html, /id="journey-video-prelude"[\s\S]*?class="journey-video-prelude-meditator"[^>]*src="video\/meditator\.png"/, 'the meditator image should lead the prelude');
assert.match(html, /id="journey-video-prelude-toggle"[\s\S]*?data-i18n="ui\.includeVideoIntroduction"/, 'Lobby should offer an explicit opt-in for the video introduction');
assert.match(html, /id="journey-video-prelude-toggle"[\s\S]*?data-i18n="ui\.videoIntroductionSubtitle"/, 'The Lobby video option should identify the Cosmic Consciousness introduction');
assert.match(html, /id="journey-video-prelude"[\s\S]*?id="journey-video-prelude-media"[^>]*preload="none"[^>]*playsinline[^>]*data-video-src="video\/generate\.mp4"/, 'the optional video source should be deferred until the introduction or preview is selected');
assert.doesNotMatch(html, /<source[^>]+src="video\/generate\.mp4"/, 'the browser must not discover the optional video through a child source at page parse time');
assert.match(html, /id="journey-video-prelude-ready"[\s\S]*?data-i18n="ui\.journeyVideoPreludeReminder"[\s\S]*?data-i18n="ui\.journeyVideoPreludeLoading"[\s\S]*?id="play-journey-video-prelude"[\s\S]*?data-i18n="ui\.playJourneyVideoPrelude"/, 'the prelude should show the interruption reminder, loading status, and explicit localized Play control');
assert.doesNotMatch(html, /skip-journey-video-prelude/, 'the prelude should not offer a skip path once the guide begins it');
assert.match(css, /\.journey-video-prelude\s*\{[\s\S]*?position:\s*fixed[\s\S]*?inset:\s*0[\s\S]*?z-index:\s*100100/, 'the video prelude should fill the application viewport');
assert.match(css, /\.journey-video-prelude video\s*\{[\s\S]*?object-fit:\s*cover[\s\S]*?background:\s*#000[\s\S]*?transition:\s*opacity 2\.4s/, 'the video fills the screen in any orientation (owner decision 2026-10-08: no black bands; upright screens trim the sides)');
assert.doesNotMatch(css.slice(css.indexOf('.journey-video-prelude video {'), css.indexOf('}', css.indexOf('.journey-video-prelude video {'))), /aspect-ratio|object-fit:\s*contain/, 'the video no longer letterboxes to a fixed 16:9 box');
assert.match(css, /\.journey-video-prelude-meditator\s*\{[\s\S]*?inset:\s*0[\s\S]*?width:\s*100%[\s\S]*?height:\s*100%[\s\S]*?object-fit:\s*cover/, 'the opening image fills the screen the same way');
assert.match(css, /\.journey-video-prelude-ready\s*\{[\s\S]*?max-height:\s*calc\(100dvh - 2rem\)[\s\S]*?overflow-y:\s*auto/, 'the loading card fits short landscape screens');
assert.match(fs.readFileSync(new URL('../manifest.json', import.meta.url), 'utf8'), /"orientation":\s*"any"/, 'the installed app turns with the device');
assert.match(html, /id="journey-video-prelude-loading"[\s\S]*?id="journey-video-prelude-progress" class="journey-video-prelude-progress" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"[\s\S]*?id="journey-video-prelude-percent"[\s\S]*?id="play-journey-video-prelude"/, 'a progress meter shows the loading status');
assert.match(prelude, /setProgress\(percent\) \{[\s\S]*?style\.width[\s\S]*?aria-valuenow[\s\S]*?progressPercent\.textContent/, 'the meter shows a bar, an accessible value and a percentage');
assert.match(prelude, /const updateProgress = \(\) => \{[\s\S]*?getBufferedAheadSeconds\(\) \/ target[\s\S]*?const updateBufferCountdown = \(\) => \{\s*updateProgress\(\);/, 'the meter follows the measured buffer on every loading tick');
assert.match(prelude, /bufferVideoToSafePoint\(\)\.then[\s\S]*?setProgress\(100\)/, 'the meter reaches 100% when Begin introduction appears');
assert.match(css, /#app:fullscreen\s*\{[\s\S]*?height:\s*100vh[\s\S]*?min-height:\s*100vh/, 'fullscreen should use a stable viewport height');
assert.match(css, /#app:fullscreen \.journey-video-prelude\s*\{[\s\S]*?width:\s*100%[\s\S]*?height:\s*100%/, 'the prelude should fill the stable fullscreen container');
assert.match(css, /\.journey-video-prelude\.is-playing \.journey-video-prelude-ready[\s\S]*?backdrop-filter:\s*none[\s\S]*?box-shadow:\s*none/, 'playback should remove expensive loading-card compositing');
assert.match(css, /\.journey-video-prelude\.is-video \.journey-video-prelude-shade\s*\{\s*opacity:\s*0/, 'actual video playback must remove the dark shade so the video remains fully visible.');
assert.match(app, /const JOURNEY_VIDEO_PRELUDE_FADE_IN_SECONDS = 2\.4/);
assert.match(app, /const JOURNEY_VIDEO_PRELUDE_FADE_OUT_SECONDS = 0\.25/);
assert.match(app, /const JOURNEY_VIDEO_PRELUDE_FAILURE_FADE_SECONDS = 1\.2/);
assert.match(app, /const JOURNEY_VIDEO_PRELUDE_MEDITATOR_HOLD_SECONDS = 3/);
assert.match(app, /const JOURNEY_VIDEO_PRELUDE_BUFFER_MIN_SECONDS = 4/);
assert.match(app, /const JOURNEY_VIDEO_PRELUDE_BUFFER_MAX_SECONDS = 8/);
assert.match(app, /const JOURNEY_VIDEO_PRELUDE_BUFFER_STABILITY_MS = 750/);
assert.match(prelude, /getVideoBufferTargetSeconds\(\)[\s\S]*?effectiveType[\s\S]*?downlink/, 'the prelude should adapt its initial buffer target to connection conditions');
assert.match(prelude, /async bufferVideoToSafePoint\(\)[\s\S]*?readyState < HTMLMediaElement\.HAVE_FUTURE_DATA[\s\S]*?getBufferedAheadSeconds\(\)[\s\S]*?JOURNEY_VIDEO_PRELUDE_BUFFER_STABILITY_MS/, 'the prelude should wait for a measured stable initial buffer');
assert.match(prelude, /Slow first-use delivery is not a media failure[\s\S]*?setTimeout\(\(\) => finish\(true\), 90000\)/, 'buffer timeout must not silently skip the video prelude');
assert.match(prelude, /getBufferedAheadSeconds\(\)[\s\S]*?JOURNEY_VIDEO_PRELUDE_REBUFFER_SECONDS|JOURNEY_VIDEO_PRELUDE_REBUFFER_SECONDS[\s\S]*?getBufferedAheadSeconds\(\)/, 'the prelude should define a playback rebuffer safety threshold');
assert.match(app, /const JOURNEY_VIDEO_PRELUDE_REBUFFER_SECONDS = 2/);
assert.match(app, /const JOURNEY_VIDEO_PRELUDE_RESUME_BUFFER_SECONDS = 4/);
assert.match(prelude, /isWaitingForBuffer[\s\S]*?JOURNEY_VIDEO_PRELUDE_RESUME_BUFFER_SECONDS/, 'the prelude should resume only after a meaningful recovery buffer');
assert.match(prelude, /remaining <= JOURNEY_VIDEO_PRELUDE_REBUFFER_SECONDS\) return/, 'short clips should not enter impossible end-of-video recovery');
assert.match(prelude, /addEventListener\('waiting', onWaiting\)[\s\S]*?addEventListener\('stalled', onWaiting\)/, 'native media stalls should enter the recovery path');
assert.match(prelude, /this\.playButton\.hidden = true[\s\S]*?bufferVideoToSafePoint\(\)\.then[\s\S]*?this\.playButton\.hidden = false/, 'the Begin control should appear only after the safe buffer is ready');
assert.match(prelude, /bufferCountdownTimer[\s\S]*?getVideoBufferTargetSeconds\(\)[\s\S]*?getBufferedAheadSeconds\(\)/, 'the prelude should show a live buffer countdown while loading');
assert.match(css, /\.journey-video-prelude\.is-playing,[\s\S]*?cursor: none/, 'the pointer should be hidden during cinematic playback');
assert.match(prelude, /is-meditator[\s\S]*?setTimeout\(\(\) => \{[\s\S]*?is-video/, 'the meditator image should dissolve into the video after a short hold');
assert.match(prelude, /this\.media\.load\(\)/, 'the supplied video should be explicitly prepared for native buffering after a user request');
assert.doesNotMatch(prelude.slice(prelude.indexOf('constructor('), prelude.indexOf('getVideoBufferTargetSeconds()')), /this\.media\?\.load\(\)/, 'constructing the prelude must not start loading the optional video');
assert.match(prelude, /ensureVideoSource\(\)[\s\S]*?this\.media\.src = source[\s\S]*?async bufferVideoToSafePoint\(\)\s*\{\s*if \(!this\.ensureVideoSource\(\)\)/, 'selected playback attaches the deferred media URL before buffering');
assert.match(css, /\.journey-video-prelude\s*\{[\s\S]*?--journey-video-visual-opacity:\s*1/, 'the prelude should render its image and video fully opaque.');
assert.match(css, /\.journey-video-prelude\.is-meditator \.journey-video-prelude-meditator[\s\S]*?opacity: var\(--journey-video-visual-opacity\)[\s\S]*?\.journey-video-prelude\.is-video \.journey-video-prelude-meditator[\s\S]*?opacity: 0/, 'the image-to-video transition should crossfade cleanly at full opacity.');
assert.match(css, /\.journey-video-prelude-ready\s*\{[\s\S]*?background:\s*rgba\(0, 0, 0, 0\.88\)/, 'the loading and Begin content should use a highly legible backing.');
assert.doesNotMatch(css, /#app\s*\{[^}]*opacity:/, 'the #app ancestor must not dim the video prelude or its readable content.');
assert.match(css, /\.journey-video-prelude\.is-leaving[\s\S]*?transition-duration:\s*0\.25s/, 'the short prelude should dissolve only across its final 0.25 seconds');
assert.match(html, /id="settings-vol-video"[^>]*min="0\.02"[^>]*max="0\.5"[\s\S]*?id="preview-video-audio"/, 'Settings should provide a safe dedicated Video Volume control and preview action');
assert.match(prelude, /class JourneyVideoPrelude[\s\S]*?async previewAudio\(\)[\s\S]*?this\.audio\.fadeJourneyVideoPrelude\(state\.volVideo, 0\.25\)[\s\S]*?const onPlay = \(\) => \{[\s\S]*?const playback = this\.media\.play\(\)[\s\S]*?fadeJourneyVideoPrelude\(state\.volVideo, JOURNEY_VIDEO_PRELUDE_FADE_IN_SECONDS\)/, 'preview and actual video playback should use the independent Video Volume');
assert.doesNotMatch(app, /fadeJourneyVideoPrelude\(state\.volMusic, JOURNEY_VIDEO_PRELUDE_FADE_IN_SECONDS\)/, 'video playback must not follow the background Music Volume');
assert.doesNotMatch(app, /requestFullscreen\(|webkitEnterFullscreen/, 'the prelude should not trigger automatic fullscreen');
assert.match(app, /state\.journeyVideoPreludeEnabled && !bypassLobbyVideoPreludeOnce[\s\S]*?await loadJourneyVideoPrelude\(\)[\s\S]*?prelude\.play\(\)[\s\S]*?startMeditationBtn\.click\(\)/, 'the selected Lobby video should load on demand, run once and then enter the normal journey dispatcher');
assert.match(app, /let journeyVideoPrelude = null[\s\S]*?function loadJourneyVideoPrelude\(\)[\s\S]*?journeyVideoPreludeLoadPromise[\s\S]*?script\.src = new URL\('\.\/modules\/journey-video-prelude\.js\?v=1\.1'[\s\S]*?journeyVideoPreludeLoadPromise = null/, 'the optional controller should load once on demand and reset its promise after failure');
assert.doesNotMatch(app, /new JourneyVideoPrelude\(audio\)/, 'the optional controller must not be constructed eagerly at startup');
assert.match(prelude, /window\.ChakraJourneyVideoPrelude = JourneyVideoPrelude/, 'the optional controller must expose its constructor to the loader');
assert.match(app, /function validateLobbyStartBeforePrelude\(\)[\s\S]*?journeyRouting\.resolveLaunchRoute[\s\S]*?journeyRouting\.validateLobbyStart[\s\S]*?notify\(t\(.ui\.noticeSelectChakra.\)\)[\s\S]*?startMeditationBtn\.addEventListener\('click', async \(\) => \{[\s\S]*?if \(!validateLobbyStartBeforePrelude\(\)\) return;[\s\S]*?state\.journeyVideoPreludeEnabled/,
    'A normal journey with no chakras must be rejected at the original Begin click, before the optional video prelude starts.');
assert.doesNotMatch(app, /this\.media\.pause\(\);[\s\S]{0,250}this\.exitFullscreen\(\);[\s\S]{0,250}this\.overlay\.classList\.remove/, 'the prelude should not leave fullscreen during the video-to-journey handoff');
assert.doesNotMatch(app, /journeyVideoPrelude\.exitFullscreen\(\)/, 'the app should not exit user-controlled fullscreen');
assert.match(prelude, /this\.media\.pause\(\);[\s\S]*?this\.audio\.fadeJourneyVideoPrelude\(0, 0\);/, 'the ready screen should leave the video paused and silent before Play');
assert.match(app, /this\.journeyVideoPreludeSource = this\.ctx\.createMediaElementSource\(media\)/, 'video audio should enter the Web Audio graph');
assert.match(app, /this\.journeyVideoPreludeGain\.connect\(this\.spatialMusicPanner\)[\s\S]*?this\.journeyVideoPreludeGain\.connect\(this\.musicEchoSend\)/, 'video audio should use the established Spatial Sound and Music Space paths');
const journeyVideoPrelude = prelude;
assert.doesNotMatch(journeyVideoPrelude, /onSkip|skipButton|JOURNEY_VIDEO_PRELUDE_SKIP/, 'the video prelude implementation should not retain an automatic skip path');
assert.match(prelude, /const onError = \(\) => \{ void complete\('unavailable', JOURNEY_VIDEO_PRELUDE_FAILURE_FADE_SECONDS\); \}/, 'video failure should safely continue to the prepared journey');
assert.match(app, /document\.getElementById\('restart-meditation'\)\?\.addEventListener\('click', async \(\) => \{[\s\S]*?meditation\.stop\(\{ preserveScreen: true \}\);[\s\S]*?bypassLobbyVideoPreludeOnce = true;[\s\S]*?startMeditationBtn\.click\(\)/, 'Restart should immediately relaunch without replaying the Lobby-only video');
assert.match(fs.readFileSync(new URL('../modules/session-stop.js', import.meta.url), 'utf8'), /const returnScreen = owner\.isExperimentActive \? experimentScreen : lobbyScreen;[\s\S]*?if \(!preserveScreen\) showScreen\(returnScreen\)/, 'the meditation stop path should keep the active screen in place only during a restart');
assert.match(`${app}\n${prelude}`, /const DND_REMINDER_FALLBACK = "Before we begin:[\s\S]*?showDndReminderIfNeeded\(\) \{[\s\S]*?if \(this\.dndReminderAcknowledged\)[\s\S]*?this\.dndReminderAcknowledged = false;[\s\S]*?const reminder = t\('ui\.journeyVideoPreludeReminder'\);[\s\S]*?notify\(reminder === 'ui\.journeyVideoPreludeReminder' \? DND_REMINDER_FALLBACK : reminder\);/, 'the reminder should be consumed once after a completed video while normal starts retain a human-readable fallback');
assert.doesNotMatch(sw, /video\/nature-upgrade\.mp4/, 'the large prelude must not be pre-cached during PWA installation');
assert.match(css, /#app:fullscreen\s*\{[\s\S]*?max-width:\s*none[\s\S]*?min-height:\s*100dvh/, 'the persistent fullscreen app should not retain the normal narrow Lobby width');
assert.match(html, /id="fullscreen-controls-reveal-zone"/, 'fullscreen should provide a dedicated bottom-edge reveal zone');
assert.match(app, /const journeyChrome = new window\.ChakraJourneyChrome\(\);/, 'the app should create an independent shared journey-chrome owner');
assert.match(journeyChrome, /document\.addEventListener\('fullscreenchange', this\.syncFullscreenJourneyChrome\)[\s\S]*?syncFullscreenJourneyChrome\(\) \{[\s\S]*?document\.body\.classList\.toggle\('journey-fullscreen-active', isJourneyFullscreen\)/, 'the shared module should explicitly track whether the persistent app container is fullscreen');
assert.match(journeyChrome, /this\.revealZone\?\.addEventListener\('pointerenter',[\s\S]*?setFullscreenChromeVisible\(true\)/, 'bottom edge hover reveals journey controls');
assert.match(css, /body\.journey-controls-active #controls:not\(\.hidden\)[\s\S]*?opacity:\s*0[\s\S]*?body\.journey-controls-active\.fullscreen-controls-visible #controls:not\(\.hidden\)[\s\S]*?opacity:\s*1/, 'the timer remains within controls and follows their fullscreen reveal state');
assert.doesNotMatch(css, /session-countdown-layer/, 'fullscreen no longer maintains a separate top-timer visibility layer');

for (const locale of locales) {
    assert.ok(locale.ui.journeyVideoPreludeReminder?.trim(), 'each shipped locale needs the interruption reminder');
    assert.ok(locale.ui.journeyVideoPreludeLoading?.trim(), 'each shipped locale needs the video loading status');
    assert.ok(locale.ui.journeyVideoPreludeProgress?.trim(), 'each shipped locale names the loading meter');
    assert.ok(locale.ui.playJourneyVideoPrelude?.trim(), 'each shipped locale needs the explicit Play label');
    assert.ok(locale.ui.includeVideoIntroduction?.trim(), 'each shipped locale needs the Lobby video-introduction option');
    assert.ok(locale.ui.videoIntroductionSubtitle?.trim(), 'each shipped locale needs the Cosmic Consciousness subtitle');
    assert.ok(locale.ui.roadmapVideoIntroduction?.trim(), 'each shipped locale needs the video roadmap label');
    assert.ok(locale.ui.musicVideoVolume?.trim(), 'each shipped locale needs the shared Music / Video Volume label');
}

assert.match(app, /function journeyT\(path\) \{\s*return t\(path, state\.language\);\s*\}/, 'journey labels should resolve against Meditation Language rather than Display Language');
assert.match(openingStage, /title\.textContent = journeyT\('ui\.preparation'\);/, 'the Preparation stage should use the narrated language');
assert.match(openingStage, /journeyT\('ui\.moon'\)[\s\S]*?journeyT\('ui\.gratitude'\)[\s\S]*?journeyT\('ui\.intention'\)/, 'all reflective journey headings should use the narrated language');
assert.match(app, /journeyT\('ui\.corpsePose'\)/, 'Corpse Pose title should use the narrated language');
assert.match(careSession, /journeyT\('ui\.purification'\)[\s\S]*?journeyT\('ui\.guideReadyForNextSession'\)/, 'care-stage and guide titles should use the narrated language');
assert.match(yogaSession, /journeyT\('ui\.yoga'\)[\s\S]*?journeyT\('ui\.yogaSubtitle'\)/, 'Yoga headings should use the narrated language');

console.log('Journey video prelude contract passed.');
